services:
  postgres:
    image: pg_analyze_training_image
    build: ./pg
    command: ["postgres", "-c", "max_connections=200"]
    container_name: pg_analyze
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
    volumes:
      - ../:/training
